/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: MK22FX512Axxx12
package_id: MK22FX512AVLQ12
mcu_data: ksdk2_0
processor_version: 3.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT}
  - {pin_num: '7', peripheral: LLWU, signal: 'P, 2', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: '8', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0}
  - {pin_num: '5', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD5}
  - {pin_num: '6', peripheral: SUPPLY, signal: 'VSS, 0', pin_signal: VSS6}
  - {pin_num: '16', peripheral: SUPPLY, signal: 'VDD, 1', pin_signal: VDD16}
  - {pin_num: '17', peripheral: SUPPLY, signal: 'VSS, 1', pin_signal: VSS17}
  - {pin_num: '18', peripheral: SUPPLY, signal: 'VSS, 2', pin_signal: VSS22}
  - {pin_num: '23', peripheral: ADC0, signal: 'DP, 1', pin_signal: ADC0_DP1}
  - {pin_num: '25', peripheral: ADC1, signal: 'DP, 1', pin_signal: ADC1_DP1}
  - {pin_num: '27', peripheral: ADC0, signal: 'DP, 0', pin_signal: ADC0_DP0/ADC1_DP3}
  - {pin_num: '29', peripheral: ADC1, signal: 'DP, 0', pin_signal: ADC1_DP0/ADC0_DP3}
  - {pin_num: '31', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '32', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '32', peripheral: ADC1, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '33', peripheral: ADC0, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '33', peripheral: ADC1, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '34', peripheral: SUPPLY, signal: 'VSSA, 0', pin_signal: VSSA}
  - {pin_num: '35', peripheral: CMP2, signal: 'IN, 2', pin_signal: ADC1_SE16/CMP2_IN2/ADC0_SE22}
  - {pin_num: '35', peripheral: ADC1, signal: 'SE, 16', pin_signal: ADC1_SE16/CMP2_IN2/ADC0_SE22}
  - {pin_num: '43', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD53}
  - {pin_num: '44', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS54}
  - {pin_num: '45', peripheral: UART4, signal: TX, pin_signal: ADC0_SE17/PTE24/UART4_TX/EWM_OUT_b}
  - {pin_num: '46', peripheral: UART4, signal: RX, pin_signal: ADC0_SE18/PTE25/UART4_RX/EWM_IN}
  - {pin_num: '50', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/JTAG_TCLK/SWD_CLK/EZP_CLK}
  - {pin_num: '51', peripheral: JTAG, signal: TDI, pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI}
  - {pin_num: '52', peripheral: JTAG, signal: TDO, pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO}
  - {pin_num: '53', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO}
  - {pin_num: '56', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD66}
  - {pin_num: '58', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM0_CH3/CLKOUTb/TRACE_CLKOUT}
  - {pin_num: '59', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3}
  - {pin_num: '64', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA}
  - {pin_num: '65', peripheral: LLWU, signal: 'P, 4', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB}
  - {pin_num: '70', peripheral: SUPPLY, signal: 'VDD, 4', pin_signal: VDD80}
  - {pin_num: '71', peripheral: SUPPLY, signal: 'VSS, 5', pin_signal: VSS81}
  - {pin_num: '73', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1}
  - {pin_num: '74', peripheral: RCM, signal: RESET, pin_signal: RESET_b}
  - {pin_num: '80', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTA29/FBa_A24}
  - {pin_num: '7', peripheral: GPIOE, signal: 'GPIO, 4', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: '2', peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN}
  - {pin_num: '55', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/USB_CLKIN/FTM0_CH2/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
  - {pin_num: '57', peripheral: SUPPLY, signal: 'VSS, 4', pin_signal: VSS67}
  - {pin_num: '65', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB}
  - {pin_num: '66', peripheral: SPI0, signal: PCS0_SS, pin_signal: PTA14/SPI0_PCS0/UART0_TX/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1}
  - {pin_num: '67', peripheral: SPI0, signal: SCK, pin_signal: PTA15/SPI0_SCK/UART0_RX/I2S0_RXD0}
  - {pin_num: '68', peripheral: SPI0, signal: SOUT, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/I2S0_RX_FS/I2S0_RXD1}
  - {pin_num: '69', peripheral: SPI0, signal: SIN, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/I2S0_MCLK}
  - {pin_num: '83', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3}
  - {pin_num: '81', peripheral: LLWU, signal: 'P, 5', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA}
  - {pin_num: '81', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA}
  - {pin_num: '84', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/FTM0_FLT0}
  - {pin_num: '82', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB}
  - {pin_num: '87', peripheral: FB, signal: 'AD, 23', pin_signal: ADC1_SE12/PTB6/FBa_AD23}
  - {pin_num: '88', peripheral: FB, signal: 'AD, 22', pin_signal: ADC1_SE13/PTB7/FBa_AD22}
  - {pin_num: '89', peripheral: FB, signal: 'AD, 21', pin_signal: PTB8/UART3_RTS_b/FBa_AD21}
  - {pin_num: '90', peripheral: FB, signal: 'AD, 20', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FBa_AD20}
  - {pin_num: '91', peripheral: FB, signal: 'AD, 19', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FBa_AD19/FTM0_FLT1}
  - {pin_num: '92', peripheral: FB, signal: 'AD, 18', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FBa_AD18/FTM0_FLT2}
  - {pin_num: '93', peripheral: SUPPLY, signal: 'VSS, 6', pin_signal: VSS105}
  - {pin_num: '94', peripheral: SUPPLY, signal: 'VDD, 5', pin_signal: VDD106}
  - {pin_num: '95', peripheral: FB, signal: 'AD, 17', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FBa_AD17/EWM_IN}
  - {pin_num: '96', peripheral: FB, signal: 'AD, 16', pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FBa_AD16/EWM_OUT_b}
  - {pin_num: '97', peripheral: FB, signal: 'AD, 15', pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FBa_AD15/FTM2_QD_PHA}
  - {pin_num: '98', peripheral: FB, signal: OE, pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FBa_OE_b/FTM2_QD_PHB}
  - {pin_num: '103', peripheral: FB, signal: 'AD, 14', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/FBa_AD14/I2S0_TXD1}
  - {pin_num: '104', peripheral: FB, signal: 'AD, 13', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FBa_AD13/I2S0_TXD0}
  - {pin_num: '105', peripheral: FB, signal: 'AD, 12', pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FBa_AD12/I2S0_TX_FS}
  - {pin_num: '106', peripheral: FB, signal: CLKOUT, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUTa/CLKOUT/I2S0_TX_BCLK}
  - {pin_num: '107', peripheral: SUPPLY, signal: 'VSS, 7', pin_signal: VSS119}
  - {pin_num: '108', peripheral: SUPPLY, signal: 'VDD, 6', pin_signal: VDD120}
  - {pin_num: '109', peripheral: FB, signal: 'AD, 11', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FBa_AD11/CMP1_OUT}
  - {pin_num: '110', peripheral: FB, signal: 'AD, 10', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FBa_AD10/CMP0_OUT/FTM0_CH2}
  - {pin_num: '111', peripheral: FB, signal: 'AD, 9', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FBa_AD9/I2S0_MCLK}
  - {pin_num: '112', peripheral: FB, signal: 'AD, 8', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FBa_AD8}
  - {pin_num: '113', peripheral: FB, signal: 'AD, 7', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FBa_AD7}
  - {pin_num: '114', peripheral: FB, signal: 'AD, 6', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FBa_AD6/FTM2_FLT0}
  - {pin_num: '115', peripheral: FB, signal: 'AD, 5', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FBa_AD5}
  - {pin_num: '116', peripheral: FB, signal: RW, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FBa_RW_b}
  - {pin_num: '119', peripheral: FB, signal: 'AD, 25', pin_signal: PTC14/UART4_RX/FBa_AD25}
  - {pin_num: '120', peripheral: FB, signal: 'AD, 24', pin_signal: PTC15/UART4_TX/FBa_AD24}
  - {pin_num: '121', peripheral: SUPPLY, signal: 'VSS, 8', pin_signal: VSS133}
  - {pin_num: '122', peripheral: SUPPLY, signal: 'VDD, 7', pin_signal: VDD134}
  - {pin_num: '127', peripheral: FB, signal: CS1_ALE_TS, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FBa_ALE/FBa_CS1_b/FBa_TS_b}
  - {pin_num: '128', peripheral: FB, signal: CS0, pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FBa_CS0_b}
  - {pin_num: '129', peripheral: FB, signal: 'AD, 4', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FBa_AD4/I2C0_SCL}
  - {pin_num: '130', peripheral: FB, signal: 'AD, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FBa_AD3/I2C0_SDA}
  - {pin_num: '131', peripheral: FB, signal: 'AD, 2', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FBa_AD2/EWM_IN}
  - {pin_num: '132', peripheral: FB, signal: 'AD, 1', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FBa_AD1/EWM_OUT_b}
  - {pin_num: '133', peripheral: FB, signal: 'AD, 0', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FBa_AD0/FTM0_FLT0}
  - {pin_num: '134', peripheral: SUPPLY, signal: 'VSS, 9', pin_signal: VSS146}
  - {pin_num: '135', peripheral: SUPPLY, signal: 'VDD, 8', pin_signal: VDD147}
  - {pin_num: '137', peripheral: UART5, signal: RX, pin_signal: PTD8/I2C0_SCL/UART5_RX/FBa_A16}
  - {pin_num: '138', peripheral: UART5, signal: TX, pin_signal: PTD9/I2C0_SDA/UART5_TX/FBa_A17}
  - {pin_num: '141', peripheral: FB, signal: 'A, 20', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FBa_A20}
  - {pin_num: '142', peripheral: FB, signal: 'A, 21', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FBa_A21}
  - {pin_num: '143', peripheral: FB, signal: 'A, 22', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FBa_A22}
  - {pin_num: '144', peripheral: FB, signal: 'A, 23', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FBa_A23}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
	gpio_pin_config_t OutConfig;

	OutConfig.pinDirection = kGPIO_DigitalOutput;
	OutConfig.outputLogic = 0;

    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA0 (pin 50) is configured as JTAG_TCLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt7);

    /* PORTA1 (pin 51) is configured as JTAG_TDI */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt7);

    /* PORTA12 (pin 64) is configured as PTA12 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAsGpio);

    /* PORTA13 (pin 65) is configured as PTA13, LLWU_P4 */
    PORT_SetPinMux(PORTA, 13U, kPORT_MuxAsGpio);

    /* PORTA14 (pin 66) is configured as SPI0_PCS0 */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAlt2);

    /* PORTA15 (pin 67) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt2);

    /* PORTA16 (pin 68) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAlt2);

    /* PORTA17 (pin 69) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt2);

    /* PORTA19 (pin 73) is configured as PTA19 */
    PORT_SetPinMux(PORTA, 19U, kPORT_MuxAsGpio);

    /* PORTA2 (pin 52) is configured as JTAG_TDO */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt7);

    /* PORTA29 (pin 80) is configured as PTA29 */
    PORT_SetPinMux(PORTA, 29U, kPORT_MuxAsGpio);

    /* PORTA3 (pin 53) is configured as JTAG_TMS */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt7);

    /* PORTA5 (pin 55) is configured as PTA5 */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAsGpio);

    /* PORTA6 (pin 58) is configured as PTA6 */
    PORT_SetPinMux(PORTA, 6U, kPORT_MuxAsGpio);

    /* PORTA7 (pin 59) is configured as PTA7 */
    PORT_SetPinMux(PORTA, 7U, kPORT_MuxAsGpio);

    /* PORTB0 (pin 81) is configured as PTB0, LLWU_P5 */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAsGpio);

    /* PORTB1 (pin 82) is configured as PTB1 */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAsGpio);

    /* PORTB10 (pin 91) is configured as FBa_AD19 */
    PORT_SetPinMux(PORTB, 10U, kPORT_MuxAlt5);

    /* PORTB11 (pin 92) is configured as FBa_AD18 */
    PORT_SetPinMux(PORTB, 11U, kPORT_MuxAlt5);

    /* PORTB16 (pin 95) is configured as FBa_AD17 */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt5);

    /* PORTB17 (pin 96) is configured as FBa_AD16 */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt5);

    /* PORTB18 (pin 97) is configured as FBa_AD15 */
    PORT_SetPinMux(PORTB, 18U, kPORT_MuxAlt5);

    /* PORTB19 (pin 98) is configured as FBa_OE_b */
    PORT_SetPinMux(PORTB, 19U, kPORT_MuxAlt5);

    /* PORTB2 (pin 83) is configured as I2C0_SCL */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt2);

    /* PORTB3 (pin 84) is configured as I2C0_SDA */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt2);

    /* PORTB6 (pin 87) is configured as FBa_AD23 */
    PORT_SetPinMux(PORTB, 6U, kPORT_MuxAlt5);

    /* PORTB7 (pin 88) is configured as FBa_AD22 */
    PORT_SetPinMux(PORTB, 7U, kPORT_MuxAlt5);

    /* PORTB8 (pin 89) is configured as FBa_AD21 */
    PORT_SetPinMux(PORTB, 8U, kPORT_MuxAlt5);

    /* PORTB9 (pin 90) is configured as FBa_AD20 */
    PORT_SetPinMux(PORTB, 9U, kPORT_MuxAlt5);

    /* PORTC0 (pin 103) is configured as FBa_AD14 */
    PORT_SetPinMux(PORTC, 0U, kPORT_MuxAlt5);

    /* PORTC1 (pin 104) is configured as FBa_AD13 */
    PORT_SetPinMux(PORTC, 1U, kPORT_MuxAlt5);

    /* PORTC10 (pin 115) is configured as FBa_AD5 */
    PORT_SetPinMux(PORTC, 10U, kPORT_MuxAlt5);

    /* PORTC11 (pin 116) is configured as FBa_RW_b */
    PORT_SetPinMux(PORTC, 11U, kPORT_MuxAlt5);

    /* PORTC14 (pin 119) is configured as FBa_AD25 */
    PORT_SetPinMux(PORTC, 14U, kPORT_MuxAlt5);

    /* PORTC15 (pin 120) is configured as FBa_AD24 */
    PORT_SetPinMux(PORTC, 15U, kPORT_MuxAlt5);

    /* PORTC2 (pin 105) is configured as FBa_AD12 */
    PORT_SetPinMux(PORTC, 2U, kPORT_MuxAlt5);

    /* PORTC3 (pin 106) is configured as CLKOUT */
    PORT_SetPinMux(PORTC, 3U, kPORT_MuxAlt5);

    /* PORTC4 (pin 109) is configured as FBa_AD11 */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt5);

    /* PORTC5 (pin 110) is configured as FBa_AD10 */
    PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt5);

    /* PORTC6 (pin 111) is configured as FBa_AD9 */
    PORT_SetPinMux(PORTC, 6U, kPORT_MuxAlt5);

    /* PORTC7 (pin 112) is configured as FBa_AD8 */
    PORT_SetPinMux(PORTC, 7U, kPORT_MuxAlt5);

    /* PORTC8 (pin 113) is configured as FBa_AD7 */
    PORT_SetPinMux(PORTC, 8U, kPORT_MuxAlt5);

    /* PORTC9 (pin 114) is configured as FBa_AD6 */
    PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt5);

    /* PORTD0 (pin 127) is configured as FBa_CS1_b */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAlt5);

    /* PORTD1 (pin 128) is configured as FBa_CS0_b */
    PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt5);

    /* PORTD12 (pin 141) is configured as FBa_A20 */
    PORT_SetPinMux(PORTD, 12U, kPORT_MuxAsGpio); //Flash WP/ACC
    GPIO_PinInit(GPIOD,12U,&OutConfig);
    GPIO_PinWrite(GPIOD,12U,1);

    /* PORTD13 (pin 142) is configured as FBa_A21 */
    PORT_SetPinMux(PORTD, 13U, kPORT_MuxAsGpio); //Flash RY/BY

    /* PORTD14 (pin 143) is configured as FBa_A22 */
    PORT_SetPinMux(PORTD, 14U, kPORT_MuxAsGpio); //Flash BYTE
    GPIO_PinInit(GPIOD,14U,&OutConfig);
    //GPIO_PinWrite(GPIOD,14U,0); //Remove later -- this is for single-step testing
    GPIO_PinWrite(GPIOD,14U,1);

    /* PORTD15 (pin 144) is configured as FBa_A23 */
    PORT_SetPinMux(PORTD, 15U, kPORT_MuxAsGpio); //Flash Reset
    GPIO_PinInit(GPIOD,15U,&OutConfig);
    GPIO_PinWrite(GPIOD,15U,1);

    /* PORTD2 (pin 129) is configured as FBa_AD4 */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt5);

    /* PORTD3 (pin 130) is configured as FBa_AD3 */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt5);

    /* PORTD4 (pin 131) is configured as FBa_AD2 */
    PORT_SetPinMux(PORTD, 4U, kPORT_MuxAlt5);

    /* PORTD5 (pin 132) is configured as FBa_AD1 */
    PORT_SetPinMux(PORTD, 5U, kPORT_MuxAlt5);

    /* PORTD6 (pin 133) is configured as FBa_AD0 */
    PORT_SetPinMux(PORTD, 6U, kPORT_MuxAlt5);

    /* PORTD8 (pin 137) is configured as UART5_RX */
    PORT_SetPinMux(PORTD, 8U, kPORT_MuxAlt3);

    /* PORTD9 (pin 138) is configured as UART5_TX */
    PORT_SetPinMux(PORTD, 9U, kPORT_MuxAlt3);

    /* PORTE0 (pin 1) is configured as I2C1_SDA */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt6);

    /* PORTE1 (pin 2) is configured as I2C1_SCL */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt6);

    /* PORTE24 (pin 45) is configured as UART4_TX */
    PORT_SetPinMux(PORTE, 24U, kPORT_MuxAlt3);

    /* PORTE25 (pin 46) is configured as UART4_RX */
    PORT_SetPinMux(PORTE, 25U, kPORT_MuxAlt3);

    /* PORTE4 (pin 7) is configured as PTE4, LLWU_P2 */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAsGpio);

    /* PORTE5 (pin 8) is configured as PTE5 */
    PORT_SetPinMux(PORTE, 5U, kPORT_MuxAsGpio);

    SIM->SOPT2 = ((SIM->SOPT2 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT2_CLKOUTSEL_MASK)))

                  /* CLKOUT select: FlexBus CLKOUT. */
                  | SIM_SOPT2_CLKOUTSEL(SOPT2_CLKOUTSEL_FLEXBUS));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
